### ISSUE TITLE
storage database at default system GO path

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/GO-file-database#8]
Currently, the  database store i.e., warehouse is being created at the address where the Save() functions are being called. This would lead to multiple warehouse folders creations if the addresses to the Save are changed. To resolve this, create a single warehouse at the System-Level GO path, and perform all db operations from there itself. 

## keep in mind
The process should be easy in implementing, by just adding the system path to GO, just before "warehouse/".

### henceforth
all db operations would work just like other commercial filebased-DBs like sqllite, JSONDB

**Comment by Harkishen-Singh** [comment]
@muskankhedia  please have a look

**Comment by muskankhedia** [comment]
Yaa sure understood, will surely try to solve it.
